//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMBO.DSDMobile.ElectronicServices.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIMBO.DSDMobile.ElectronicServices.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap btn_back_up {
            get {
                object obj = ResourceManager.GetObject("btn_back_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_BackwardsArrow_down {
            get {
                object obj = ResourceManager.GetObject("Btn_BackwardsArrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_BackwardsArrow_focused {
            get {
                object obj = ResourceManager.GetObject("Btn_BackwardsArrow_focused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_BackwardsArrow_up {
            get {
                object obj = ResourceManager.GetObject("Btn_BackwardsArrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_forward_up {
            get {
                object obj = ResourceManager.GetObject("btn_forward_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_ForwardArrow_down {
            get {
                object obj = ResourceManager.GetObject("Btn_ForwardArrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_ForwardArrow_focused {
            get {
                object obj = ResourceManager.GetObject("Btn_ForwardArrow_focused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_ForwardArrow_up {
            get {
                object obj = ResourceManager.GetObject("Btn_ForwardArrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación.
        /// </summary>
        internal static string hlbConfirmacion {
            get {
                return ResourceManager.GetString("hlbConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Electronica.
        /// </summary>
        internal static string hlbFirmaElectronica {
            get {
                return ResourceManager.GetString("hlbFirmaElectronica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recolección.
        /// </summary>
        internal static string hlbRecoleccion {
            get {
                return ResourceManager.GetString("hlbRecoleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de Barras.
        /// </summary>
        internal static string lblCodigoBarras {
            get {
                return ResourceManager.GetString("lblCodigoBarras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto a Recolectar:.
        /// </summary>
        internal static string lblCollectedAmount {
            get {
                return ResourceManager.GetString("lblCollectedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor de Escanear el Codigo de Barras.
        /// </summary>
        internal static string lblLeyenda1 {
            get {
                return ResourceManager.GetString("lblLeyenda1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generado por la TPV!!!!!.
        /// </summary>
        internal static string lblLeyenda2 {
            get {
                return ResourceManager.GetString("lblLeyenda2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Mandatory {
            get {
                object obj = ResourceManager.GetObject("Mandatory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string MessageBoxHeader {
            get {
                return ResourceManager.GetString("MessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVERTENCIA!!!!!\nSe registrara la excepción?.
        /// </summary>
        internal static string MSG_ADVERTENCIA {
            get {
                return ResourceManager.GetString("MSG_ADVERTENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGENCIA:.
        /// </summary>
        internal static string MSG_AGENCIA {
            get {
                return ResourceManager.GetString("MSG_AGENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***********************************.
        /// </summary>
        internal static string MSG_ASTERISCOS {
            get {
                return ResourceManager.GetString("MSG_ASTERISCOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***********************************.
        /// </summary>
        internal static string MSG_ASTERISCOS_2 {
            get {
                return ResourceManager.GetString("MSG_ASTERISCOS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta Codigo de Barras.
        /// </summary>
        internal static string MSG_BARCODE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_BARCODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARGO POR SERVICIO.
        /// </summary>
        internal static string MSG_CARGO {
            get {
                return ResourceManager.GetString("MSG_CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo por Servicio:.
        /// </summary>
        internal static string msg_CargoMinusculas {
            get {
                return ResourceManager.GetString("msg_CargoMinusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIENTE:.
        /// </summary>
        internal static string MSG_CLIENTE {
            get {
                return ResourceManager.GetString("MSG_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Erroneo.
        /// </summary>
        internal static string MSG_CODIGO_ERRONEO {
            get {
                return ResourceManager.GetString("MSG_CODIGO_ERRONEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COL 1..
        /// </summary>
        internal static string MSG_COL1 {
            get {
                return ResourceManager.GetString("MSG_COL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COL 2..
        /// </summary>
        internal static string MSG_COL2 {
            get {
                return ResourceManager.GetString("MSG_COL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COL 3..
        /// </summary>
        internal static string MSG_COL3 {
            get {
                return ResourceManager.GetString("MSG_COL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea Salir?.
        /// </summary>
        internal static string MSG_CONFIRMACION {
            get {
                return ResourceManager.GetString("MSG_CONFIRMACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmacion de Monto Incorrecta!!!.
        /// </summary>
        internal static string msg_ConfirmacionIncorrecta {
            get {
                return ResourceManager.GetString("msg_ConfirmacionIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea hacer Recoleccion?.
        /// </summary>
        internal static string MSG_DESEA_RECOLECCION {
            get {
                return ResourceManager.GetString("MSG_DESEA_RECOLECCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string msg_error {
            get {
                return ResourceManager.GetString("msg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excede Monto maximo SE por Ruta, monto disponible.
        /// </summary>
        internal static string msg_ExcedeMontoRuta {
            get {
                return ResourceManager.GetString("msg_ExcedeMontoRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA:.
        /// </summary>
        internal static string MSG_FECHA {
            get {
                return ResourceManager.GetString("MSG_FECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORA:.
        /// </summary>
        internal static string MSG_HORA {
            get {
                return ResourceManager.GetString("MSG_HORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion.
        /// </summary>
        internal static string msg_information {
            get {
                return ResourceManager.GetString("msg_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA X CARGO.
        /// </summary>
        internal static string MSG_IVA_X_CARGO {
            get {
                return ResourceManager.GetString("MSG_IVA_X_CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRACIAS POR UTILIZAR ESTE SERVICIO!!!.
        /// </summary>
        internal static string MSG_LEYENDA_BLM {
            get {
                return ResourceManager.GetString("MSG_LEYENDA_BLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA DUDAS O ACLARACIONES DE ESTA.
        /// </summary>
        internal static string MSG_LEYENDA_BLM1 {
            get {
                return ResourceManager.GetString("MSG_LEYENDA_BLM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERACION, FAVOR DE LLAMAR AL .
        /// </summary>
        internal static string MSG_LEYENDA_BLM2 {
            get {
                return ResourceManager.GetString("MSG_LEYENDA_BLM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENTRO DE ATENCION A CLIENTES.
        /// </summary>
        internal static string MSG_LEYENDA_BLM3 {
            get {
                return ResourceManager.GetString("MSG_LEYENDA_BLM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 800 681 9622 LADA SIN COSTO.
        /// </summary>
        internal static string MSG_LEYENDA_BLM4 {
            get {
                return ResourceManager.GetString("MSG_LEYENDA_BLM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTO ABONADO:.
        /// </summary>
        internal static string MSG_MONTO_ABONAR {
            get {
                return ResourceManager.GetString("MSG_MONTO_ABONAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTO RECOLECTADO.
        /// </summary>
        internal static string MSG_MONTO_RECOLECTADO {
            get {
                return ResourceManager.GetString("MSG_MONTO_RECOLECTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Abonar:.
        /// </summary>
        internal static string msg_MontoAbonarMinus {
            get {
                return ResourceManager.GetString("msg_MontoAbonarMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto SE no puede ser cero.
        /// </summary>
        internal static string msg_MontoCero {
            get {
                return ResourceManager.GetString("msg_MontoCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excede Monto maximo SE para este cliente, monto disponible.
        /// </summary>
        internal static string msg_MontoMaximoCliente {
            get {
                return ResourceManager.GetString("msg_MontoMaximoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto SE no puede ser menor a cero.
        /// </summary>
        internal static string msg_MontoMenorCero {
            get {
                return ResourceManager.GetString("msg_MontoMenorCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Recolectado:.
        /// </summary>
        internal static string msg_MontoRecolectadoMinus {
            get {
                return ResourceManager.GetString("msg_MontoRecolectadoMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto SE no puede estar vacio.
        /// </summary>
        internal static string msg_MontoVacio {
            get {
                return ResourceManager.GetString("msg_MontoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. CLIENTE:.
        /// </summary>
        internal static string MSG_NO_CLIENTE {
            get {
                return ResourceManager.GetString("MSG_NO_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto no puede tener decimales.
        /// </summary>
        internal static string msg_NoDecimales {
            get {
                return ResourceManager.GetString("msg_NoDecimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto SE no puede ser alfanumerico.
        /// </summary>
        internal static string msg_NoLetras {
            get {
                return ResourceManager.GetString("msg_NoLetras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUTA:.
        /// </summary>
        internal static string MSG_RUTA {
            get {
                return ResourceManager.GetString("MSG_RUTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARGO POR SERVICIO:.
        /// </summary>
        internal static string MSG_TICKET_LIQ_CARGO {
            get {
                return ResourceManager.GetString("MSG_TICKET_LIQ_CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ****** RECOLECCIONES SE*******.
        /// </summary>
        internal static string MSG_TICKET_LIQ_LEYENDA {
            get {
                return ResourceManager.GetString("MSG_TICKET_LIQ_LEYENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTO RECOLECTADO:.
        /// </summary>
        internal static string MSG_TICKET_LIQ_MONTO {
            get {
                return ResourceManager.GetString("MSG_TICKET_LIQ_MONTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTO TOTAL RECOLECTADO:.
        /// </summary>
        internal static string MSG_TICKET_LIQ_TOTAL {
            get {
                return ResourceManager.GetString("MSG_TICKET_LIQ_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. DE TRANSACCIONES:.
        /// </summary>
        internal static string MSG_TICKET_LIQ_TRANSACCIONES {
            get {
                return ResourceManager.GetString("MSG_TICKET_LIQ_TRANSACCIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRMA ELECTRONICA.
        /// </summary>
        internal static string MSG_TITULO_FIRMA {
            get {
                return ResourceManager.GetString("MSG_TITULO_FIRMA", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Operations_focus {
            get {
                object obj = ResourceManager.GetObject("Operations_focus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Operations_up {
            get {
                object obj = ResourceManager.GetObject("Operations_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Optional {
            get {
                object obj = ResourceManager.GetObject("Optional", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string rb1 {
            get {
                return ResourceManager.GetString("rb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        internal static string rb11 {
            get {
                return ResourceManager.GetString("rb11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        internal static string rb2 {
            get {
                return ResourceManager.GetString("rb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        internal static string rb3 {
            get {
                return ResourceManager.GetString("rb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800.
        /// </summary>
        internal static string rb4 {
            get {
                return ResourceManager.GetString("rb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string rb5 {
            get {
                return ResourceManager.GetString("rb5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200.
        /// </summary>
        internal static string rb6 {
            get {
                return ResourceManager.GetString("rb6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1400.
        /// </summary>
        internal static string rb7 {
            get {
                return ResourceManager.GetString("rb7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1600.
        /// </summary>
        internal static string rb8 {
            get {
                return ResourceManager.GetString("rb8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800.
        /// </summary>
        internal static string rb9 {
            get {
                return ResourceManager.GetString("rb9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string rbBack {
            get {
                return ResourceManager.GetString("rbBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string rbNext {
            get {
                return ResourceManager.GetString("rbNext", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Reports_focus {
            get {
                object obj = ResourceManager.GetObject("Reports_focus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reports_up {
            get {
                object obj = ResourceManager.GetObject("Reports_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Electronica.
        /// </summary>
        internal static string RPT_FIRMA_ELECTRONICA {
            get {
                return ResourceManager.GetString("RPT_FIRMA_ELECTRONICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE HHc_Clientes ADD IMP_SE_CLIENTE INT DEFAULT 0.
        /// </summary>
        internal static string SQL_ALTER_HHc_Clientes {
            get {
                return ResourceManager.GetString("SQL_ALTER_HHc_Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table HHc_CargosSE
        ///(
        ///ID_RUTA 	 varchar(4)	 not null,
        ///ID_CARGO         integer         not null,
        ///MONTO_COMISION   integer         not null,
        ///MINIMO           integer         not null,
        ///MAXIMO           integer         not null,
        ///IVA_COMISION     float           not null,
        ///constraint       PK_HHc_CargosSE primary key(ID_RUTA, ID_CARGO)
        ///).
        /// </summary>
        internal static string SQL_CREATE_HHc_CargosSE {
            get {
                return ResourceManager.GetString("SQL_CREATE_HHc_CargosSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table HHc_RecoleccionesSE
        ///(
        ///ID_RUTA                        varchar(4)    not null,
        ///ID_CLIENTE                   varchar(15)   not null,
        ///FECHA                     date          not null,
        ///HORA                       time          not null,
        ///PIN_DINAMICO     varchar(30)   null,
        ///PIN_TRANS        varchar(30)   null,
        ///MONTO            int           not null,
        ///CARGO            int           null,
        ///STATUS           int           not null,
        ///IMPRESO          int           not null,
        ///constraint       PK_HH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_CREATE_HHc_RecoleccionesSE {
            get {
                return ResourceManager.GetString("SQL_CREATE_HHc_RecoleccionesSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(*)
        ///from systable a inner join syscolumn b
        ///on a.object_id = b.table_id
        ///where a.table_name =&apos;HHc_Clientes&apos;
        ///and b.column_name = &apos;IMP_SE_CLIENTE&apos;.
        /// </summary>
        internal static string SQL_EXIST_IMP_SE_CLIENTE {
            get {
                return ResourceManager.GetString("SQL_EXIST_IMP_SE_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(CONVERT(int, IMP_SE_CLIENTE), 0)
        ///FROM HHc_Clientes 
        ///WHERE ID_CLIENTE = ?.
        /// </summary>
        internal static string SQL_GET_AMOUNT_X_CLIENT {
            get {
                return ResourceManager.GetString("SQL_GET_AMOUNT_X_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MONTO_COMISION, 0)
        ///FROM HHc_CargosSE  
        ///WHERE MAXIMO &gt;= ?
        ///AND MINIMO&lt;= ?.
        /// </summary>
        internal static string SQL_GET_CARGO {
            get {
                return ResourceManager.GetString("SQL_GET_CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID_RUTA, FECHA, HORA,PIN_DINAMICO, MONTO, CARGO,  IMPRESO 
        ///FROM HHc_RecoleccionesSE 
        ///WHERE ID_CLIENTE = ?.
        /// </summary>
        internal static string SQL_GET_COLLECTION_CLIENT_DATA {
            get {
                return ResourceManager.GetString("SQL_GET_COLLECTION_CLIENT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(COUNT(*), 0)
        ///FROM HHc_RecoleccionesSE 
        ///WHERE ID_CLIENTE = ?.
        /// </summary>
        internal static string SQL_GET_COLLECTION_X_CLIENT {
            get {
                return ResourceManager.GetString("SQL_GET_COLLECTION_X_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(CONVERT(int, valor), 0)
        ///FROM HHc_Configuraciones
        ///WHERE ID_RUTA = ?
        ///AND PARAMETRO = &apos;IMP_SE_RUTA&apos;.
        /// </summary>
        internal static string SQL_GET_COLLECTION_X_ROUTE {
            get {
                return ResourceManager.GetString("SQL_GET_COLLECTION_X_ROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID_DATO,RENGLON,COLUMNA,ALINEACION,ES_DETALLE,FORMATO from HHc_Coordenadas WHERE ID_TIPO_DOCUMENTO=? ORDER BY RENGLON.
        /// </summary>
        internal static string SQL_GET_COORDENADAS_VALUES {
            get {
                return ResourceManager.GetString("SQL_GET_COORDENADAS_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(IVA_COMISION, 0)
        ///FROM HHc_CargosSE  
        ///WHERE MAXIMO &gt;= ?
        ///AND MINIMO&lt;= ?.
        /// </summary>
        internal static string SQL_GET_IVA_X_CARGO {
            get {
                return ResourceManager.GetString("SQL_GET_IVA_X_CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SUM(MONTO), SUM(CARGO), (SUM(MONTO) + SUM(CARGO)) , COUNT(ID_CLIENTE) 
        ///FROM  HHc_RecoleccionesSE.
        /// </summary>
        internal static string SQL_GET_LIQ_INFO {
            get {
                return ResourceManager.GetString("SQL_GET_LIQ_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(CONVERT(int, valor), 0)
        ///FROM HHc_Configuraciones
        ///WHERE ID_RUTA = ?
        ///AND PARAMETRO = &apos;APLICA_IVA_SE&apos;.
        /// </summary>
        internal static string SQL_GET_MOSTRAR_IVAXCARGO {
            get {
                return ResourceManager.GetString("SQL_GET_MOSTRAR_IVAXCARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(COUNT(*),0) FROM 
        ///HHc_RecoleccionesSE 
        ///WHERE ID_CLIENTE= ? AND IMPRESO = 0.
        /// </summary>
        internal static string SQL_GET_PENDING {
            get {
                return ResourceManager.GetString("SQL_GET_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(CONVERT(int, valor), 0)
        ///FROM HHc_Configuraciones
        ///WHERE ID_RUTA = ?
        ///AND PARAMETRO = &apos;APLICA_PIN_TRANS&apos;.
        /// </summary>
        internal static string SQL_GET_PIN_TRANS {
            get {
                return ResourceManager.GetString("SQL_GET_PIN_TRANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(SUM(MONTO) + SUM(CARGO),0)  FROM HHc_RecoleccionesSE.
        /// </summary>
        internal static string SQL_GET_TOTAL_COLLECTED_AMOUNT {
            get {
                return ResourceManager.GetString("SQL_GET_TOTAL_COLLECTED_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HHc_RecoleccionesSE VALUES 
        ///(?, ?, ?, ?, ?, ?, ?, ?, ?, ?).
        /// </summary>
        internal static string SQL_INSERT_RECOLECCCIONES_SE {
            get {
                return ResourceManager.GetString("SQL_INSERT_RECOLECCCIONES_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE HHc_RecoleccionesSE SET IMPRESO = ? WHERE ID_CLIENTE = ?.
        /// </summary>
        internal static string SQL_UPDATE_IMPRESO {
            get {
                return ResourceManager.GetString("SQL_UPDATE_IMPRESO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE HHc_RecoleccionesSE SET PIN_TRANS = ?,  STATUS = ? WHERE ID_CLIENTE = ?.
        /// </summary>
        internal static string SQL_UPDATE_RECOLECCIONES_SE {
            get {
                return ResourceManager.GetString("SQL_UPDATE_RECOLECCIONES_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800.
        /// </summary>
        internal static string STR_NO_REPORTE {
            get {
                return ResourceManager.GetString("STR_NO_REPORTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1900.
        /// </summary>
        internal static string STR_NO_REPORTE_LIQ {
            get {
                return ResourceManager.GetString("STR_NO_REPORTE_LIQ", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tab_background {
            get {
                object obj = ResourceManager.GetObject("tab_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap task_failed {
            get {
                object obj = ResourceManager.GetObject("task_failed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap task_inprogress {
            get {
                object obj = ResourceManager.GetObject("task_inprogress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap task_succeeded {
            get {
                object obj = ResourceManager.GetObject("task_succeeded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
